### ISSUE TITLE
I just crashed the site I was downloading...

### ISSUE THREAD

**Issue by bwells78** [s0ph1e/node-website-scraper#129]
Is there away to throttle the crawler to make its requests more manageable?

**Comment by s0ph1e** [comment]
Hi @bwells78 
What do you mean in *more manageable*?

**Comment by bwells78** [comment]
Hi @s0ph1e - I'm was referring to a way to randomize the time between requests or slow them down so that they don't overwhelm the web server on the other end.  Not a major issue for me right now, but I was experimenting with your package and hosed our web server for a couple minutes accidentally.  It hit capacity and didn't respond for a few minutes but then came back.  Great work, though- thank you!

**Comment by s0ph1e** [comment]
Seems there are some issues with web server - it should not crash because of one scraping.
But as I received couple of similar questions I'll think about adding some option for delay between requests.
Thanks!

**Comment by bwells78** [comment]
Thank you!
