### ISSUE TITLE
Error when scraping URL with email address

### ISSUE THREAD

**Issue by mgreen-spraymarketing** [s0ph1e/node-website-scraper#140]
I get the following error when scraping a site with an email address in the URL. This may just be a co-incidence. I've renamed the domain and email address for data protection purposes. 

Unhandled rejection Error: ENOENT: no such file or directory, open '/tmp/www.example.org/forums/users/simonblogs@hotmail.com/

**Comment by s0ph1e** [comment]
Hi @mgreen-spraymarketing 
I've tried to reproduce it locally, but for me scraping url with email works good, file is saving correctly.

Could you please clarify
* what version of module do you use
* what options do you use for module
* what OS do you use

?

Thanks

**Comment by mgreen-spraymarketing** [comment]
Thanks for getting back. I'm currently using MacOS Sierra with the latest module version. Options are below:

// req.user.domain is the site URL

    var options = {
        urls: ['http://'+req.user.domain],
        urlFilter: function (url) {
            return (
                url.indexOf('http://'+req.user.domain) === 0 ||
                url.indexOf('https://'+req.user.domain) === 0
            )
        },
        recursive: true,
        maxDepth: 100,
        prettifyUrls: true,
        filenameGenerator: 'bySiteStructure',
        directory: tmpPath,
        sources: [
            { selector: 'img', attr: 'src' },
            { selector: 'link[rel="stylesheet"]', attr: 'href' },
            { selector: 'script', attr: 'src' }
        ]
    };

**Comment by s0ph1e** [comment]
Hi @mgreen-spraymarketing 
This bug is fixed in version 1.2.1
