### ISSUE TITLE
Ability to pipe download to a client

### ISSUE THREAD

**Issue by milos1290** [s0ph1e/node-website-scraper#154]
I was wondering if it is possible to not download anything on the server side and just forward the download directly to requesting client ?

Basically it would pipe it as a response back to client.

**Comment by s0ph1e** [comment]
Hi @milos1290 

No, it is not possible because this project is just node.js (server) module which saves files for given url. It doesn't implement any client interaction.

**Comment by s0ph1e** [comment]
If you have more questions feel free to open new issue
