### ISSUE TITLE
Consider using Phantomjs (or something else) to download dynamic websites

### ISSUE THREAD

**Issue by s0ph1e** [s0ph1e/node-website-scraper#169]

**Comment by s0ph1e** [comment]
Will be implemented using custom `httpResponseHandler` #188 and phantom html plugin https://github.com/s0ph1e/node-website-scraper-phantom-html

**Comment by botaniQQQ** [comment]
How to use plugin?

**Comment by s0ph1e** [comment]
Hi. Plugin is not ready yet.
You can follow https://github.com/s0ph1e/node-website-scraper-phantom-html to get notifications when it will be released
