### ISSUE TITLE
How can I download a website that needs to have a login session?

### ISSUE THREAD

**Issue by solancer** [s0ph1e/node-website-scraper#180]
How can I download a website that needs to have a login session?

**Comment by s0ph1e** [comment]
Hi 
You can log in manually to needed site, copy cookies and set copied value to `Cookie` header in request options

Something like this:
```js
scrape({
  urls: ['http://nodejs.org/'],
  directory: '/path/to/save/',
  request: {
    headers: {
     Cookie: "key1=value1;" // cookies from real page after logging in
    }
  }
})
```

**Comment by solancer** [comment]
Thanks that was damn easy! 

I just had to copy the cookies from the dev-tools > Network > copy request as cUrl

You should probably add this to the docs cause it's a damn useful feature.

**Comment by s0ph1e** [comment]
I'm glad that it solved your issue)
Docs contain info about `request` options, but I should probably extend it with some examples. Thanks
