### ISSUE TITLE
favicon.ico is saved as HTML when response is 404

### ISSUE THREAD

**Issue by Flamenco** [s0ph1e/node-website-scraper#185]
This is the content of some of my favicon.ico files:

<img width="386" alt="screen shot 2017-02-23 at 12 01 49 pm" src="https://cloud.githubusercontent.com/assets/819940/23270028/6fce42c8-f9c0-11e6-9b91-b4939063b4c8.png">

I would suggest not saving the file at all when the request returns a 404.

**Comment by s0ph1e** [comment]
Hi
It downloads exactly what server returns)

From one side, it makes sense to reject everything with status code !== 200, but from another side - it makes sense to save everything server returns. In both cases we will have errors - 404 file not found in scraped site in 1st case and html instead of icon in second case.

I think about adding some customization to http response handling, so soon it will be possible to reject almost everything you don't need

Thanks for great idea!

**Comment by Flamenco** [comment]
The problem is that when I open the scraped version, it returns a 200 with an invalid favicon file.

**Comment by s0ph1e** [comment]
Yes, I understand.
But it is expected behavior - for example if we want to save github's 404 page https://github.com/something-not-found

**Comment by Flamenco** [comment]
Why not save it as something like foo.ico.404.err. And log it. Then you could do something like go back to your unreachable resources and check them at a later time.  As it is now, we have no way of knowing was unreachable.   Yet again a reason of why the header data is important. I'm not suggesting that scraper saves the header, just makes it available.

**Comment by s0ph1e** [comment]
From version [2.2.0](https://github.com/s0ph1e/node-website-scraper/releases/tag/v2.2.0) you can customize resource loading by using `httpResponseHandler` option and log success/failed resources using `onResourceSaved`/`onResourceError` callbacks.
It will be something like this:
```javascript
scrape({
  urls: ['http://example.com/'],
  directory: '/path/to/save',
  httpResponseHandler: (response) => {
    if (response.statusCode === 404) {
        return Promise.reject(new Error('status is 404'));
    } else {
        return Promise.resolve(response.body) // here you also can return headers
    }
  },
  onResourceSaved: (resource) => {
    console.log(`Resource ${resource} was saved to fs`);
  },
  onResourceError: (resource, err) => {
    console.log(`Resource ${resource} was not saved because of ${err}`);
  }
})
```

Hope it helps
