### ISSUE TITLE
Support not downloading, but json output only

### ISSUE THREAD

**Issue by sslash** [s0ph1e/node-website-scraper#19]
Would it make sense for this project to support returning the urls of the parsed assets, and not physically downloading the files?

**Comment by s0ph1e** [comment]
Hi @sslash 

Do you mean return something like this?
```javascript
[
  {
    url: 'http://example.com',
    assets: [
      { url: 'http://example.com/cat.png' }
      { url: 'http://example.com/blog.html', assets: [ /* assets here */ ] }
    ]
  }
]
```

Yes, I think it makes sense, but requires large changes to project.

From my point of view next steps are required to implement this functionality:
* Return tree of all resources (now only flat array for options.urls are returned)
* Add flag to options which allows skip downloading

**Comment by sslash** [comment]
Yes! Absolutely, it would be really really nice. I've forked the project and hacked it together for my own need, but the code is horrible

**Comment by s0ph1e** [comment]
It is possible to skip downloading files using option `resourceSaver` added in [release 2.3.0](https://github.com/s0ph1e/node-website-scraper/releases/tag/v2.3.0)

See https://github.com/s0ph1e/node-website-scraper/blob/978a31168531236112eb7dc598f5d4dde1e26a0c/README.md#resourcesaver
