### ISSUE TITLE
Gzip compressed files

### ISSUE THREAD

**Issue by botaniQQQ** [s0ph1e/node-website-scraper#195]
Hello.

`.css` and `.js` files not save to `/css/`, `/js/` folder if use Gzip (.gzip, .gz) compressed.

```
<link rel="stylesheet" type="text/css" href="/typo3temp/compressor/merged-8c0f80a4734546a979de6a45f1e89479-7484a557f428c68edb3058885ecab2dc.css.gzip?1485359665" media="all">
<script src="/typo3temp/compressor/merged-7bdb5bc3b96ce4e5c4bda2daee269592-4a0fc9bd8484f1ec9c0427b8545f89a1.js.gzip?1474281289" type="text/javascript"></script>
```

Can you do something about this?

**Comment by botaniQQQ** [comment]
```
scrape.defaults.subdirectories.forEach(function (directory, i) {
    if (scrape.defaults.subdirectories[i].directory == 'js') {
        scrape.defaults.subdirectories[i] = { directory: 'js', extensions: ['.js','.js.gz','.js.gzip'] };
    }
    else if (scrape.defaults.subdirectories[i].directory == 'css') {
        scrape.defaults.subdirectories[i] = { directory: 'css', extensions: ['.css','.css.gz','.css.gzip'] };
    }
});
```

And add `subdirectories`, not save to `/js/` or `/css/`

**Comment by aivus** [comment]
Hello, @botaniQQQ 

You can specify rules by using options.
See [here](https://github.com/s0ph1e/node-website-scraper#subdirectories)

Default rules could be found [here](https://github.com/s0ph1e/node-website-scraper/blob/master/lib/config/defaults.js).

I don't think that we have to save gzipped files to js/css by default.

**Comment by s0ph1e** [comment]
It will not save `.gz.css` to `css` folder even if subdirectory is set to 
```javascript
{ directory: 'css', extensions: ['.css','.css.gz','.css.gzip'] }
```
because extension of resource is **.gz**, not **.css.gz**. It takes last part after `.`

I think best approach in this case is to write custom `filenameGenerator` taking [byType filename generator](https://github.com/s0ph1e/node-website-scraper/blob/51a14466df012e7bc982029dea499ece05241f06/lib/filename-generator/by-type.js) as a basis

**Comment by botaniQQQ** [comment]
@aivus, @s0ph1e Thanks for the answer.

Could you show me how it works `byType`?

**Comment by s0ph1e** [comment]
Options [filenameGenerator](https://github.com/s0ph1e/node-website-scraper#filenamegenerator) can contain a functions, so you should add something like this:

```javascript
scrape({
  urls: ['http://example.com/'],
  directory: '/path/to/save'
  filenameGenerator: (resource, options, occupiedFileNames) => {
    /* your code here 
     you can copy main logic from
     https://github.com/s0ph1e/node-website-scraper/blob/master/lib/filename-generator/by-type.js 
     and change it */
  }
})
```
