### ISSUE TITLE
Cant't download website with fontawesome

### ISSUE THREAD

**Issue by anstak** [s0ph1e/node-website-scraper#197]
I try to download Fontawesome.com for example. But I got errors:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND fontawesome-webfont.woff 
Failed to load resource: net::ERR_FILE_NOT_FOUND fontawesome-webfont.ttf 
```
ETC...

**Comment by s0ph1e** [comment]
Hi @anstak 
Could you please provide steps to reproduce and full options object that you use? 
Thanks

**Comment by anstak** [comment]
Hi @s0ph1e 
I tested with parameters:
```
var options = {
	urls: ["http://fontawesome.io"],
	directory: folder,
	recursive: true,
	maxDepth: 1,
	urlFilter: function(url){ return url.indexOf("http://fontawesome.io") === 0; }		
};
```
**It is not download fonts.** 

BUT if I set `maxDepth: 2`  - it is working!
I think its some kind of bug, becouse I want to set maxDepth = 1...

**Comment by s0ph1e** [comment]
it happens because now `maxDepth` is applied to all types of resources - fonts, styles, images, etc. 
I think it can be improved by using depth only for links. Will do that when I have some free time

**Comment by anstak** [comment]
I see... I think better to download all links inside css files!

**Comment by s0ph1e** [comment]
Starting from version 2.4.0 you can use option `maxRecusriveDepth` to limit depth only for hyperlinks, other resources will be downloaded regardless of their depth.
