### ISSUE TITLE
not able to download some resources

### ISSUE THREAD

**Issue by enamulubc** [s0ph1e/node-website-scraper#204]
I was trying to download a page where within the javascript of the page, a json file was loaded. But the scrapper could not downloaded that JSON file. Moreover, the path for that json file was specified using relative path (e.g., /../../foo.json), so I could not render the downloaded page as that relative path did not work anymore in my local directory.

Any thoughts on fixing this problem?

**Comment by s0ph1e** [comment]
Hi @enamulubc 

As it is described [in readme](https://github.com/s0ph1e/node-website-scraper/tree/978a31168531236112eb7dc598f5d4dde1e26a0c#introduction)
> **Note:** by default dynamic websites (where content is loaded by js) may be saved not correctly because `website-scraper` doesn't execute js, it only parses http responses for html and css files. If you need to download dynamic website take a look on [website-scraper-phantom](https://github.com/s0ph1e/node-website-scraper-phantom).

So it is expected behavior. I suggest to try [website-scraper-phantom](https://github.com/s0ph1e/node-website-scraper-phantom), it might help

**Comment by enamulubc** [comment]
I tried  website-scraper-phantom, but the issue persists. The json file that was requested from within the json file was not downloaded.

How does the code finds resources? Does it looks within the javascript code to find resources (like json file) or does it only find resources in the header and replaces with the local resource urls?

**Comment by s0ph1e** [comment]
> How does the code finds resources?

It checks specific attributes (like `src`) of specific elements (like `<img.. />`)

> Does it looks within the javascript code to find resources (like json file)

No, it doesn't look within the javascript code to find resources.
