### ISSUE TITLE
How to call the default resource saver?

### ISSUE THREAD

**Issue by Darker** [s0ph1e/node-website-scraper#211]
I want to override resource saving for HTML files because I need to replace some things (eg. iframes) in them.

But when I use resource saver, I have to handle all files. How to call the original resource saving routing for subset of the files?

**Comment by s0ph1e** [comment]
There is no good way to do it 

As it is stored in [lib/resource-saver/index.js](https://github.com/s0ph1e/node-website-scraper/blob/master/lib/resource-saver/index.js) inside module I can suggest next workarounds:
* include it directly by fs path like 
`var defaultSaver = require('./node_modules/website-scraper/lib/resource-saver/index.js')`
* or just copy-paste it and update with your requirements

**Comment by Darker** [comment]
Thanks for the answer. Since the saver uses ES6 classes so nicely, wouldn't it be best if the it was possible to inherit? For example:

    var scrape = require('website-scraper');
    class MySaver extends scrape.BaseResourceSaver {

        // overide stuff...
    }

This is just a suggestion. I am closing this issue. I solved the whole problem by instead overriding request handler and making changes on request body.

**Comment by s0ph1e** [comment]
Yes, it makes sense. I'll consider exporting resourceSaver in future versions
Thanks for suggestion
