### ISSUE TITLE
sitemaps protocol

### ISSUE THREAD

**Issue by balazserdos** [s0ph1e/node-website-scraper#218]
Is the sitemaps protocol supported? 

I have some **static** pages where you can get only by using js based functionality.  I plan to add these pages to the sitemaps to make it scrapeable. Can I get this pages to scrape by "node-website-scraper"?
Thanks :)

**Comment by s0ph1e** [comment]
Hi @balazserdos 
For now sitemaps are not supported and you can't download pages from sitemap
