### ISSUE TITLE
(FEATURE) - on parse of new URLS, be able to set folder

### ISSUE THREAD

**Issue by gabrielcsapo** [s0ph1e/node-website-scraper#222]
In my findings I found that if a URL is parsed in a document from a HREF, it will create a sub document in the parents directory that was defined at creation time;

```javascript
scrape({
  directory: '/path/to/save'
})
```

I have created https://github.com/gabrielcsapo/node-timecapsule and the way it works is caching every URL as its own directory, with timestamped sub directories. 

I have been using this module and was wondering if it was inline with the direction of this project to be able to change the directory of the directory that the modules are being saved to.

I know there is https://github.com/s0ph1e/node-website-scraper#resourcesaver, but that section doesn't allow the static URL that was changed from the prior.

**Comment by s0ph1e** [comment]
Hi @gabrielcsapo 
I'm not sure that I completely understand your question. Could you please share some example of desired behavior?

If you need to change `directory` in runtime - you can create your custom [resourceSaver](https://github.com/s0ph1e/node-website-scraper/#resourcesaver)

If you need to change subdirectory which is generated for resource - you can create custom [filenameGenerator](https://github.com/s0ph1e/node-website-scraper/#filenamegenerator) function (you can use [default filename generator](https://github.com/s0ph1e/node-website-scraper/blob/9e21caa04ba1e963b80d7f005e450442d30457ee/lib/filename-generator/by-type.js) as example)

**Comment by gabrielcsapo** [comment]
@s0ph1e apologies so I was thinking of scenario like the following;

> http://www.google.com

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Google</title>
    </head>
    <body>
        <a href="/about"> About </a>
    </body>
</html>
```

When `node-website-scraper` goes to scrape the data from `/about` I was wondering if it would be possible to change the location and the link to point to another directory like `${hash}/about`. The href would have to have to point to the new directory also. 

I might sound rambling, but hopefully I make sense 🙈

**Comment by s0ph1e** [comment]
@gabrielcsapo I think it can be implemented with custom `filenameGenerator`. It should be something like this

```javascript
function myFilenameGenerator(resource, options, occupiedFileNames) { /* 
  here you can copy existing implementation 
  and update logic of generating subdirectory name for resource
  https://github.com/s0ph1e/node-website-scraper/blob/9e21caa04ba1e963b80d7f005e450442d30457ee/lib/filename-generator/by-type.js#L13
 */}

scrape({
  urls: urls,
  directory: directory,
  filenameGenerator: myFilenameGenerator
})
```

Hope it helps

**Comment by gabrielcsapo** [comment]
Thank you I will try this!

**Comment by gabrielcsapo** [comment]
@s0ph1e so I am getting a directory structure like this if I try to change the folder path, but what I am looking to do, is on resource, if it from a different domain then the url I am scraping, it will store it in a different folder.

<img width="270" alt="screen shot 2017-07-08 at 8 37 56 pm" src="https://user-images.githubusercontent.com/1854811/27990991-61477ce8-641d-11e7-978e-c1678764a7e3.png">

I have a work in progress branch that is located here https://github.com/gabrielcsapo/node-timecapsule/blob/wip/index.js#L52, I thought it might be too much to post in the code, but a sample snippet is

```javascript
function generateFilename (resource, options, occupiedFileNames) {
   var preferredFilename = resource.getFilename();
   var urlFilename = scrapeUtils.getFilenameFromUrl(resource.getUrl());
   var filename = preferredFilename || urlFilename || options.defaultFilename;

   var resourceType = resource.getType();
   var extension = scrapeUtils.getFilenameExtension(filename);

   if (!extension && typeExtensions[resourceType]) {
       extension = typeExtensions[resourceType][0];
       filename += extension;
   }
   const url = resource.getUrl().replace(filename, '');
   const hashUrl = url.indexOf('://') > -1 ? url.substring(url.indexOf('://') + 3, url.length) : url;
   const hash = new Buffer(hashUrl).toString('base64');
   const date = moment().format('Y-M-D-h:mm:ss:a');

   if(!self.cached[resource.getUrl()]) {
       self.cached[resource.getUrl()] = `${hash}/${date}`;
   }

   return `${self.cached[resource.getUrl()]}/${filename}`;
}
```

**Comment by s0ph1e** [comment]
@gabrielcsapo 
Resource is saved in `directory/filename` where:
* directory - root directory name, from `directory` option
* filename - path to resource inside `directory`, generated by filenameGenerator. using custom filename generator you can change only `filename` part, not `directory`

> but what I am looking to do, is on resource, if it from a different domain then the url I am scraping, it will store it in a different folder

do you mean changing `directory` part?

**Comment by gabrielcsapo** [comment]
Yes @s0ph1e, Is it possible to change the directory from the generate filename function?

**Comment by gabrielcsapo** [comment]
@s0ph1e sorry 🙈 my logic was wrong, I didn't want to do this after all.
