### ISSUE TITLE
How to scrape website with hashtag?

### ISSUE THREAD

**Issue by SuperMario360** [s0ph1e/node-website-scraper#223]
How to scrape website with hashtag?
For example, how ho scrape this landing page: https://folliclerx.com/#/es/main/
?

**Comment by gabrielcsapo** [comment]
@SuperMario360 it looks like the readme states that this tool scrapes static websites whereas https://github.com/s0ph1e/node-website-scraper-phantom will be able to scrape dynamic websites. 

> Note: by default dynamic websites (where content is loaded by js) may be saved not correctly because website-scraper doesn't execute js, it only parses http responses for html and css files. If you need to download dynamic website take a look on [website-scraper-phantom](https://github.com/s0ph1e/node-website-scraper-phantom).

**Comment by s0ph1e** [comment]
Hi @SuperMario360 
This site is rendered using js, please try to use [website-scraper-phantom](https://github.com/s0ph1e/node-website-scraper-phantom)

**Comment by SuperMario360** [comment]
web-scraper-phantom It worked perfectly. Great!
