### ISSUE TITLE
Hi I am getting this FATAL ERROR also wanted to know how to scrap after login, because when i try to scrap from dashboard it just scrap login html

### ISSUE THREAD

**Issue by mtr980** [s0ph1e/node-website-scraper#225]
GREAT TOOL. Please see below error that i am getting after it downloads about 90mb.

<--- Last few GCs --->

[9352:0x103000000]  1894565 ms: Mark-sweep 1410.2 (1809.8) -> 1410.2 (1790.8) MB, 136.5 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 137 ms) last resort 
[9352:0x103000000]  1894672 ms: Mark-sweep 1410.2 (1790.8) -> 1410.2 (1790.3) MB, 107.0 / 0.0 ms  last resort 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1cbfa5d29891 <JS Object>
    2: new constructor(aka Request) [ComputerPath/node_modules/request/request.js:130] [pc=0x1d3b394eb6bb](this=0x1e208b6d42b1 <a Request with map 0x2ca36680b471>,options=0xbefb12febe9 <an Object with map 0x29d75dc824c1>)
    4: request(aka request) [ComputerPath/node_modules/request/index.js:54] [pc=0x1d3b394eb054](this=...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewCodeRaw(int, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [/usr/local/bin/node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
 7: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*, unsigned long) [/usr/local/bin/node]
 8: v8::internal::FullCodegenCompilationJob::ExecuteJobImpl() [/usr/local/bin/node]
 9: v8::internal::CompilationJob::ExecuteJob() [/usr/local/bin/node]
10: v8::internal::(anonymous namespace)::GenerateUnoptimizedCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
11: v8::internal::(anonymous namespace)::CompileUnoptimizedCode(v8::internal::CompilationInfo*, v8::internal::Compiler::ConcurrencyMode) [/usr/local/bin/node]
12: v8::internal::(anonymous namespace)::GetUnoptimizedCode(v8::internal::CompilationInfo*, v8::internal::Compiler::ConcurrencyMode) [/usr/local/bin/node]
13: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/local/bin/node]
14: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
15: 0x1d3b3838437d
Abort trap: 6

**Comment by s0ph1e** [comment]
Hi @mtr980 

1. To scrape after login you can use `request` option, see https://github.com/s0ph1e/node-website-scraper#request

Usually websites use cookies for authorization, so you can log in manually to needed site, copy cookies and set copied value to `Cookie` header in request options

Something like this:
```js
scrape({
  urls: ['http://nodejs.org/'],
  directory: '/path/to/save/',
  request: {
    headers: {
     Cookie: "key1=value1;" // cookies from real page after logging in
    }
  }
})
```

2. As for error - looks like your website is quite large and process runs out of memory, please try to increase memory limit for node process 
```sh
node --max-old-space-size=8192 app.js  # set memory limit to 8Gb
```

**Comment by s0ph1e** [comment]
Closing this.
If you will  have more questions - feel free to open new issues
