### ISSUE TITLE
Relative path images in css files not getting saved

### ISSUE THREAD

**Issue by buildcave** [s0ph1e/node-website-scraper#48]
Hey, thank you for making this module! It's really awesome, and overcomes a lot of issues other tools like it seem to have.

I'm having an issue on some pages (ex: http://<domain>.com/index.html) where images with a relative path in the css file aren't getting downloaded.

Has this been seen before?

Trevor

**Comment by s0ph1e** [comment]
Hi @buildcave

I didn't remember such issues before

Could you please provide some url where it can be reproduced so I'll be able to find the root cause and solution? (Seems url in your previous message are cut off)

**Comment by buildcave** [comment]
Hey @s0ph1e,

Here's a URL:
http://becauseofyou.online/fbmusclegrow/index.html

When it is downloaded it seems like /img/button.png is not being downloaded.

Further are the options and how I have the scraper configured:

      var options = {
        urls: [url],
        sources: [{
          selector: 'img',
          attr: 'src'
        }, {
          selector: 'input',
          attr: 'src'
        }, {
          selector: 'object',
          attr: 'data'
        }, {
          selector: 'embed',
          attr: 'src'
        }, {
          selector: 'video',
          attr: 'src'
        }, {
          selector: 'param[name="movie"]',
          attr: 'value'
        }, {
          selector: 'script',
          attr: 'src'
        }, {
          selector: 'link[rel="stylesheet"]',
          attr: 'href'
        }, {
          selector: 'link[rel*="icon"]',
          attr: 'href'
        }],
        subdirectories: [{
          directory: 'images',
          extensions: ['.png', '.jpg', '.jpeg', '.gif']
        }, {
          directory: 'js',
          extensions: ['.js']
        }, {
          directory: 'videos',
          extensions: ['.mp4']
        }, {
          directory: 'css',
          extensions: ['.css']
        }, {
          directory: 'fonts',
          extensions: ['.ttf', '.woff', '.eot', '.svg']
        }],
        directory: stagingPath,
        request: {
          headers: {
            'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus
4 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166
Mobile Safari/535.19'
          }
        }
      }


Thank you!

Trevor

**Comment by s0ph1e** [comment]
I found the problem - module downloads image but updates only first found rule in css file
It is solved in version 0.3.6

**Comment by buildcave** [comment]
Heck ya! You're awesome thank you!
