### ISSUE TITLE
Why underscore instead of lodash?

### ISSUE THREAD

**Issue by marklagendijk** [s0ph1e/node-website-scraper#50]
I wondered why this project is using Underscore instead of Lodash. It is the first time that I see a Node.js module which uses Underscore. Lodash seems to be the default choice for nearly all projects.
There is a good reason for this: Lodash has [a lot of features](https://lodash.com/docs), which Underscore lacks.

When making my changes in this projects, I found that sometimes I wanted to use a Lodash function, which Underscore didn't have. This is bad because using such utility functions leads to easier understandable code.

Would you accept a pull request which replaced Underscore with Lodash?

**Comment by s0ph1e** [comment]
By chance
As I wrote earlier this code was written long time ago as quick solution and then migrated to module
For me it was enough but if it would be easier for other contributors to use `lodash` and you want to change it I agree with migration `underscore` -> `lodash`
