### ISSUE TITLE
Save to existing directory

### ISSUE THREAD

**Issue by s0ph1e** [s0ph1e/node-website-scraper#65]

**Comment by ppallesws** [comment]
Agreed, this seems to be a problem if trying to create a temporary directory prior to the scrape.  For now, I've simply updated scraper.js (line 101) to: return Promise.resolve();  instead of:

return Promise.reject(new Error('Path ' + dir + ' exists'));

Why are you rejecting the promise if the directory already exists?

**Comment by ppallesws** [comment]
Created a pull request to fix this: https://github.com/s0ph1e/node-website-scraper/pull/79

**Comment by s0ph1e** [comment]
Hi @ppallesws 
Thanks for your contribution

The idea that lies behind scraper was to download site to **new** directory. It is not downloading to existing directories, it is not overriding existing files. 

To be honest, I don't see problems with creating new directory.

--------

I can't merge your PR because it breaks backward compatibility. And I think implementation should be more common - it should allow not only empty directory, but any directory and it should not override existing files (like it is implemented in `wget`)

From my point of view, next steps are needed for this:
* add new option, like `allowSavingToExistingDirectory: false` (so it will not break BC)
* on initialization create list of existing files in directory
* on downloading check filename and if file exist - generate new filename (to avoid theirs overriding)
* on cleanup remove only files loaded by scraper and don't touch files that were in directory before scraping
* cover this functionality with tests

So I'm closing your PR now, but this functionality will be implemented in the future.

**Comment by botaniQQQ** [comment]
I need to get 2 pages from one site:
https://habrahabr.ru/ and https://habrahabr.ru/post/323656/
Because I would like to save in one folder.

This can be done?

**Comment by s0ph1e** [comment]
Hi @botaniQQQ 
In case you need to download 2 pages only first approach (with 2 urls in `urls`) will work.

Now it is not possible to call `scrape` twice with same directory because it was designed to use one directory per scrape.

**Comment by botaniQQQ** [comment]
Now we have to use such a not very convenient method.

```
scrape({
    urls: [
        {url: 'https://habrahabr.ru/', filename: 'index.html'}
    ],
    directory: '../sites/habrahabr.com'
});
```
```
scrape({
    urls: [
        {url: 'https://habrahabr.ru/post/323656/', filename: 'post.html'}
    ],
    directory: '../sites/habrahabr.com_tmp'
});
```
And run command:
```
cp -Rfn habrahabr.com_tmp/* habrahabr.com/ && rm -rf habrahabr.com_tmp
```

@s0ph1e What is the technical problem of saving to an existing folder?

**Comment by s0ph1e** [comment]
@botaniQQQ I see next problems here:
* resolving conflicts between generated filenames and existing files
* need to keep in mind a lot of corner cases: different access rights to files and directories, symlinks, etc.

It requires a lot of logic and it will be not a universal solution because different people may expect different behavior.

I agree that it is not very good solutions, but by using 
```
cp -Rfn habrahabr.com_tmp/* habrahabr.com/ && rm -rf habrahabr.com_tmp
```
you determine conflict resolution which is suitable for **your** task but different from my opinion how saving to existing directory should work.

**Comment by botaniQQQ** [comment]
@s0ph1e, Maybe can you enter an additional parameter that would allow saving files with the replacement of existing files?

The `fs.writeFile()` allows you to rewrite the file while saving.

That would be fine.

**Comment by aivus** [comment]
> Maybe can you enter an additional parameter that would allow saving files with the replacement of existing files?

Why replacing?
What if someone else don't want to override and want to add some suffix? Like `file.html` -> `file.1.html`?

So, merging of content is out of scope this module.

**Comment by botaniQQQ** [comment]
> Why replacing?
What if someone else don't want to override and want to add some suffix? Like file.html -> file.1.html?

No, `.html`, don`t overwrite. 
Only styles, JS, fonts files. On the whole site have the same content.
And to have the same files in each folder is not very convenient.

```
- index.html
- /css/style.css
- /js/script.js
- /post/post.html
- /post/css/style.css
- /post/js/script.js
```
That's because it would be better.
```
- index.html
- post.html
- /css/style.css
- /js/script.js
```

Wget works this way. Replace existing files and save it to the current folder.
```
wget -p -k -O index.html https://habrahabr.ru/
wget -p -k -O post.html https://habrahabr.ru/post/323656/
```

**Comment by s0ph1e** [comment]
@botaniQQQ I assume it works in this way because you set output filenames for each request. `-O index.html` - saves result to `index.html`

But if you try to download same resource twice - it will create new file
```bash
wget https://habrahabr.ru
wget https://habrahabr.ru
ls # index.html  index.html.1
```

As @aivus mentioned, everyone expects different behavior from *saving to existing directory* functionality and that's why now I'm not working on this.

`website-scraper` !== `wget` in node.js and need to remember that:
* `wget` creates directories for domains, while `website-scraper` allows to sites with different domains to same directory
* `wget` saves files by site hierarchy, while `website-scraper` allows to use site hierarchy or to separate them by custom folders
This differences make implementation of saving to existing directory more complex and less evident.

Probably `wget` is more suitable for your task?

**Comment by s0ph1e** [comment]
Closing this issue because for now I am not going to implement it

**Comment by botaniQQQ** [comment]
@s0ph1e, I checked, if you remove the check on the existence of the folder, it turns out exactly what I need.
Only one parameter will do what is needed. Please tell me how to call this variable `self.options.overwrite` in a file `lib/fs-adaper.js`?
https://github.com/botaniQQQ/node-website-scraper/commits/master

**Comment by botaniQQQ** [comment]
@s0ph1e 
![hqdefault](https://cloud.githubusercontent.com/assets/3118010/23973013/dc655030-09dc-11e7-841e-1455a97f4e1d.png)
