### ISSUE TITLE
Awesome! Would be cool to save cookies!

### ISSUE THREAD

**Issue by PrimeBagel** [s0ph1e/node-website-scraper#75]
I love this! Please make it save cookies! Request can do this but it would be a nice default option. Btw it would also be nice if there was a way to make it get only one kind of file from a site and not the rest.

**Comment by s0ph1e** [comment]
Hi @PrimeBagel 
Thanks for your feedback :)

* As for cookies - it supports them [by default](https://github.com/s0ph1e/node-website-scraper/blob/master/lib/config/defaults.js#L25) 
* Could you please provide an example of downloading only one kind of file? I'm not sure that I clearly understood what you mean

**Comment by PrimeBagel** [comment]
For example it saves all images and HTML by default but it would be nice if there was a way that you could make it only save .js files

**Comment by s0ph1e** [comment]
You need to override default options
For example, to load only js files you can follow one of next approaches:

1 Use `source` option to save files from `src` attribute of `<script>` tag
```javascript
scraper.scrape({
  urls: ['http://example.com/'],
  directory: '/path/to/save',
  sources: [
    { selector: 'script', attr: 'src' }
  ]
})
```

2 Use `urlFilter` option to filter files which ends with `.js`
```javascript
scraper.scrape({
  urls: ['http://example.com/'],
  directory: '/path/to/save',
  urlFilter: function(url){
    return _.endsWith(url, '.js');
  }
})

**Comment by aivus** [comment]
If you have some additional question - fill free to reopen
