### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by s0ph1e** [s0ph1e/node-website-scraper#80]
Add logger + option like `logLevel` (debug, warning, error, etc.)

**Comment by s0ph1e** [comment]
Use [debug](https://www.npmjs.com/package/debug) for logs because it is common practice for modules. Added in #106

**Comment by aivus** [comment]
It seems in #106 option `ignoreErrors` was added only.

But what if I want to debug how it works. (what exactly loaded and in what order)?

**Comment by s0ph1e** [comment]
Issue was about adding logger module and using `debug` was introduced in #106 
More events will be added in the process

Ok, I'll reopen it to not forget to log more events
